### PR TITLE
TUI hack drafts

### PR DESCRIPTION
**Pull request by ShaunLawrie**
I'm just trying stuff out at the moment to see what additional commandlets/output properties I could use to wrap a spectre console based tui overtop of this. It ain't pretty atm, just a torrent of bad code but I thought you might want to see it in action 😆

The main things I want to try work out are:
- How to add threading info to the timeline response. Maybe adding another command to pull the posts parent/root but I think a lot of posts only make sense given the context of the one they're replying to.
- How to expose the details of a post that you need send a reply, repost or like.

https://github.com/user-attachments/assets/a17b84f8-8b72-4e0e-bace-23eb6689deab

If you have the prerelease PwshSpectreConsole module installed and use Windows Terminal Preview (latest) it should work.

I haven't had much time to work on this but it's been fun when I can tinker.

### CODE REVIEW

**Comment by jdhitsolutions** [comment]
For the time being, I'd prefer not take any external dependencies and the fact that the user needs a preview version of Windows Terminal means I wouldn't want to merge this into a production release. But if we can integrate it and mark it as experimental that would be interesting. I'd love to have Platyps Markdown help documents for the new commands.

**Comment by jdhitsolutions** [comment]
I am incorporating your suggestion to make `$PostCache` a global-scoped variable. Not doing anything with caching profiles yet as I always want to get the most current information.

**Comment by ShaunLawrie** [comment]
> For the time being, I'd prefer not take any external dependencies and the fact that the user needs a preview version of Windows Terminal means I wouldn't want to merge this into a production release. But if we can integrate it and mark it as experimental that would be interesting. I'd love to have Platyps Markdown help documents for the new commands.

Yep cool. I'm going to take a look at what small changes I could make here to support making replies to posts that fits with the rest of the style of your module 

Something like this or maybe a dedicated reply commandlet
```pwsh
$posts = Get-BskyTimeline -Limit 10
New-BskyPost "Replying to a skeet" -ReplyTo $posts[0]
```

**Comment by ShaunLawrie** [comment]
I still want to work on building a TUI on top of this but I think it's best to keep the concerns of the UI and the PSBluesky module separate so the PSBluesky module is effectively a really good bluesky api client for powershell. Adding TUI/UI stuff in here will make it a nightmare to maintain 😆

**Pull request closed without merging**
